server.port=8080
logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/users_db
spring.datasource.username=admin
spring.datasource.password=admin

spring.main.allow-bean-definition-overriding=true

spring.kafka.bootstrap-servers: localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id: documents-group

spring.kafka.producer.topic.out=finalProject

